language: generic

services: docker

before_install:
  - docker build -t robinerickson/incubo .

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "incubo"
  env: "Incubo-env"
  bucket: "elasticbeanstalk-ca-central-1-585550510790"
  bucket_path: "incubo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
